// From react-attr-converter
export const ReactAttrConvertMap = { 
    htmlFor: 'for',
    className: 'class',
    accept: 'accept',
    acceptCharset: 'acceptcharset',
    accessKey: 'accesskey',
    action: 'action',
    allowFullScreen: 'allowfullscreen',
    allowTransparency: 'allowtransparency',
    alt: 'alt',
    async: 'async',
    autoComplete: 'autocomplete',
    autoFocus: 'autofocus',
    autoPlay: 'autoplay',
    // backgroundColor: 'bgcolor', // Doesn't work
    capture: 'capture',
    cellPadding: 'cellpadding',
    cellSpacing: 'cellspacing',
    challenge: 'challenge',
    charSet: 'charset',
    checked: 'checked',
    cite: 'cite',
    classID: 'classid',
    colSpan: 'colspan',
    cols: 'cols',
    content: 'content',
    contentEditable: 'contenteditable',
    contextMenu: 'contextmenu',
    controls: 'controls',
    coords: 'coords',
    crossOrigin: 'crossorigin',
    data: 'data',
    dateTime: 'datetime',
    default: 'default',
    defer: 'defer',
    dir: 'dir',
    disabled: 'disabled',
    download: 'download',
    draggable: 'draggable',
    encType: 'enctype',
    form: 'form',
    formAction: 'formaction',
    formEncType: 'formenctype',
    formMethod: 'formmethod',
    formNoValidate: 'formnovalidate',
    formTarget: 'formtarget',
    frameBorder: 'frameborder',
    headers: 'headers',
    height: 'height',
    hidden: 'hidden',
    high: 'high',
    href: 'href',
    hrefLang: 'hreflang',
    httpEquiv: 'httpequiv',
    icon: 'icon',
    id: 'id',
    inputMode: 'inputmode',
    integrity: 'integrity',
    is: 'is',
    keyParams: 'keyparams',
    keyType: 'keytype',
    kind: 'kind',
    label: 'label',
    lang: 'lang',
    list: 'list',
    loop: 'loop',
    low: 'low',
    manifest: 'manifest',
    marginHeight: 'marginheight',
    marginWidth: 'marginwidth',
    max: 'max',
    maxLength: 'maxlength',
    media: 'media',
    mediaGroup: 'mediagroup',
    method: 'method',
    min: 'min',
    minLength: 'minlength',
    multiple: 'multiple',
    muted: 'muted',
    name: 'name',
    noValidate: 'novalidate',
    nonce: 'nonce',
    open: 'open',
    optimum: 'optimum',
    pattern: 'pattern',
    placeholder: 'placeholder',
    poster: 'poster',
    preload: 'preload',
    profile: 'profile',
    radioGroup: 'radiogroup',
    readOnly: 'readonly',
    rel: 'rel',
    required: 'required',
    reversed: 'reversed',
    role: 'role',
    rowSpan: 'rowspan',
    rows: 'rows',
    sandbox: 'sandbox',
    scope: 'scope',
    scoped: 'scoped',
    scrolling: 'scrolling',
    seamless: 'seamless',
    selected: 'selected',
    shape: 'shape',
    size: 'size',
    sizes: 'sizes',
    span: 'span',
    spellCheck: 'spellcheck',
    src: 'src',
    srcDoc: 'srcdoc',
    srcLang: 'srclang',
    srcSet: 'srcset',
    start: 'start',
    step: 'step',
    style: 'style',
    summary: 'summary',
    tabIndex: 'tabindex',
    target: 'target',
    title: 'title',
    type: 'type',
    useMap: 'usemap',
    value: 'value',
    width: 'width',
    wmode: 'wmode',
    wrap: 'wrap',
    accentHeight: 'accentheight',
    accumulate: 'accumulate',
    additive: 'additive',
    alignmentBaseline: 'alignmentbaseline',
    allowReorder: 'allowreorder',
    alphabetic: 'alphabetic',
    amplitude: 'amplitude',
    arabicForm: 'arabicform',
    ascent: 'ascent',
    attributeName: 'attributename',
    attributeType: 'attributetype',
    autoReverse: 'autoreverse',
    azimuth: 'azimuth',
    baseFrequency: 'basefrequency',
    baseProfile: 'baseprofile',
    baselineShift: 'baselineshift',
    bbox: 'bbox',
    begin: 'begin',
    bias: 'bias',
    by: 'by',
    calcMode: 'calcmode',
    capHeight: 'capheight',
    clip: 'clip',
    clipPath: 'clippath',
    clipPathUnits: 'clippathunits',
    clipRule: 'cliprule',
    colorInterpolation: 'colorinterpolation',
    colorInterpolationFilters: 'colorinterpolationfilters',
    colorProfile: 'colorprofile',
    colorRendering: 'colorrendering',
    contentScriptType: 'contentscripttype',
    contentStyleType: 'contentstyletype',
    cursor: 'cursor',
    cx: 'cx',
    cy: 'cy',
    d: 'd',
    decelerate: 'decelerate',
    descent: 'descent',
    diffuseConstant: 'diffuseconstant',
    direction: 'direction',
    display: 'display',
    divisor: 'divisor',
    dominantBaseline: 'dominantbaseline',
    dur: 'dur',
    dx: 'dx',
    dy: 'dy',
    edgeMode: 'edgemode',
    elevation: 'elevation',
    enableBackground: 'enablebackground',
    end: 'end',
    exponent: 'exponent',
    externalResourcesRequired: 'externalresourcesrequired',
    fill: 'fill',
    fillOpacity: 'fillopacity',
    fillRule: 'fillrule',
    filter: 'filter',
    filterRes: 'filterres',
    filterUnits: 'filterunits',
    floodColor: 'floodcolor',
    floodOpacity: 'floodopacity',
    focusable: 'focusable',
    fontFamily: 'fontfamily',
    fontSize: 'fontsize',
    fontSizeAdjust: 'fontsizeadjust',
    fontStretch: 'fontstretch',
    fontStyle: 'fontstyle',
    fontVariant: 'fontvariant',
    fontWeight: 'fontweight',
    format: 'format',
    from: 'from',
    fx: 'fx',
    fy: 'fy',
    g1: 'g1',
    g2: 'g2',
    glyphName: 'glyphname',
    glyphOrientationHorizontal: 'glyphorientationhorizontal',
    glyphOrientationVertical: 'glyphorientationvertical',
    glyphRef: 'glyphref',
    gradientTransform: 'gradienttransform',
    gradientUnits: 'gradientunits',
    hanging: 'hanging',
    horizAdvX: 'horizadvx',
    horizOriginX: 'horizoriginx',
    ideographic: 'ideographic',
    imageRendering: 'imagerendering',
    in: 'in',
    in2: 'in2',
    intercept: 'intercept',
    k: 'k',
    k1: 'k1',
    k2: 'k2',
    k3: 'k3',
    k4: 'k4',
    kernelMatrix: 'kernelmatrix',
    kernelUnitLength: 'kernelunitlength',
    kerning: 'kerning',
    keyPoints: 'keypoints',
    keySplines: 'keysplines',
    keyTimes: 'keytimes',
    lengthAdjust: 'lengthadjust',
    letterSpacing: 'letterspacing',
    lightingColor: 'lightingcolor',
    limitingConeAngle: 'limitingconeangle',
    local: 'local',
    markerEnd: 'markerend',
    markerHeight: 'markerheight',
    markerMid: 'markermid',
    markerStart: 'markerstart',
    markerUnits: 'markerunits',
    markerWidth: 'markerwidth',
    mask: 'mask',
    maskContentUnits: 'maskcontentunits',
    maskUnits: 'maskunits',
    mathematical: 'mathematical',
    mode: 'mode',
    numOctaves: 'numoctaves',
    offset: 'offset',
    opacity: 'opacity',
    operator: 'operator',
    order: 'order',
    orient: 'orient',
    orientation: 'orientation',
    origin: 'origin',
    overflow: 'overflow',
    overlinePosition: 'overlineposition',
    overlineThickness: 'overlinethickness',
    paintOrder: 'paintorder',
    panose1: 'panose1',
    pathLength: 'pathlength',
    patternContentUnits: 'patterncontentunits',
    patternTransform: 'patterntransform',
    patternUnits: 'patternunits',
    pointerEvents: 'pointerevents',
    points: 'points',
    pointsAtX: 'pointsatx',
    pointsAtY: 'pointsaty',
    pointsAtZ: 'pointsatz',
    preserveAlpha: 'preservealpha',
    preserveAspectRatio: 'preserveaspectratio',
    primitiveUnits: 'primitiveunits',
    r: 'r',
    radius: 'radius',
    refX: 'refx',
    refY: 'refy',
    renderingIntent: 'renderingintent',
    repeatCount: 'repeatcount',
    repeatDur: 'repeatdur',
    requiredExtensions: 'requiredextensions',
    requiredFeatures: 'requiredfeatures',
    restart: 'restart',
    result: 'result',
    rotate: 'rotate',
    rx: 'rx',
    ry: 'ry',
    scale: 'scale',
    seed: 'seed',
    shapeRendering: 'shaperendering',
    slope: 'slope',
    spacing: 'spacing',
    specularConstant: 'specularconstant',
    specularExponent: 'specularexponent',
    speed: 'speed',
    spreadMethod: 'spreadmethod',
    startOffset: 'startoffset',
    stdDeviation: 'stddeviation',
    stemh: 'stemh',
    stemv: 'stemv',
    stitchTiles: 'stitchtiles',
    stopColor: 'stopcolor',
    stopOpacity: 'stopopacity',
    strikethroughPosition: 'strikethroughposition',
    strikethroughThickness: 'strikethroughthickness',
    string: 'string',
    stroke: 'stroke',
    strokeDasharray: 'strokedasharray',
    strokeDashoffset: 'strokedashoffset',
    strokeLinecap: 'strokelinecap',
    strokeLinejoin: 'strokelinejoin',
    strokeMiterlimit: 'strokemiterlimit',
    strokeOpacity: 'strokeopacity',
    strokeWidth: 'strokewidth',
    surfaceScale: 'surfacescale',
    systemLanguage: 'systemlanguage',
    tableValues: 'tablevalues',
    targetX: 'targetx',
    targetY: 'targety',
    textAnchor: 'textanchor',
    textDecoration: 'textdecoration',
    textLength: 'textlength',
    textRendering: 'textrendering',
    to: 'to',
    transform: 'transform',
    u1: 'u1',
    u2: 'u2',
    underlinePosition: 'underlineposition',
    underlineThickness: 'underlinethickness',
    unicode: 'unicode',
    unicodeBidi: 'unicodebidi',
    unicodeRange: 'unicoderange',
    unitsPerEm: 'unitsperem',
    vAlphabetic: 'valphabetic',
    vHanging: 'vhanging',
    vIdeographic: 'videographic',
    vMathematical: 'vmathematical',
    values: 'values',
    vectorEffect: 'vectoreffect',
    version: 'version',
    vertAdvY: 'vertadvy',
    vertOriginX: 'vertoriginx',
    vertOriginY: 'vertoriginy',
    viewBox: 'viewbox',
    viewTarget: 'viewtarget',
    visibility: 'visibility',
    widths: 'widths',
    wordSpacing: 'wordspacing',
    writingMode: 'writingmode',
    x: 'x',
    x1: 'x1',
    x2: 'x2',
    xChannelSelector: 'xchannelselector',
    xHeight: 'xheight',
    xlinkActuate: 'xlinkactuate',
    xlinkArcrole: 'xlinkarcrole',
    xlinkHref: 'xlinkhref',
    xlinkRole: 'xlinkrole',
    xlinkShow: 'xlinkshow',
    xlinkTitle: 'xlinktitle',
    xlinkType: 'xlinktype',
    xmlns: 'xmlns',
    xmlnsXlink: 'xmlnsxlink',
    xmlBase: 'xmlbase',
    xmlLang: 'xmllang',
    xmlSpace: 'xmlspace',
    y: 'y',
    y1: 'y1',
    y2: 'y2',
    yChannelSelector: 'ychannelselector',
    z: 'z',
    zoomAndPan: 'zoomandpan',
    onAbort: 'onabort',
    onAnimationEnd: 'onanimationend',
    onAnimationIteration: 'onanimationiteration',
    onAnimationStart: 'onanimationstart',
    onBlur: 'onblur',
    onCanPlay: 'oncanplay',
    onCanPlayThrough: 'oncanplaythrough',
    onChange: 'onchange',
    onClick: 'onclick',
    onCompositionEnd: 'oncompositionend',
    onCompositionStart: 'oncompositionstart',
    onCompositionUpdate: 'oncompositionupdate',
    onContextMenu: 'oncontextmenu',
    onCopy: 'oncopy',
    onCut: 'oncut',
    onDoubleClick: 'ondoubleclick',
    onDrag: 'ondrag',
    onDragEnd: 'ondragend',
    onDragEnter: 'ondragenter',
    onDragExit: 'ondragexit',
    onDragLeave: 'ondragleave',
    onDragOver: 'ondragover',
    onDragStart: 'ondragstart',
    onDrop: 'ondrop',
    onDurationChange: 'ondurationchange',
    onEmptied: 'onemptied',
    onEncrypted: 'onencrypted',
    onEnded: 'onended',
    onError: 'onerror',
    onFocus: 'onfocus',
    onInput: 'oninput',
    onKeyDown: 'onkeydown',
    onKeyPress: 'onkeypress',
    onKeyUp: 'onkeyup',
    onLoad: 'onload',
    onLoadedData: 'onloadeddata',
    onLoadedMetadata: 'onloadedmetadata',
    onLoadStart: 'onloadstart',
    onMouseDown: 'onmousedown',
    onMouseEnter: 'onmouseenter',
    onMouseLeave: 'onmouseleave',
    onMouseMove: 'onmousemove',
    onMouseOut: 'onmouseout',
    onMouseOver: 'onmouseover',
    onMouseUp: 'onmouseup',
    onPaste: 'onpaste',
    onPause: 'onpause',
    onPlay: 'onplay',
    onPlaying: 'onplaying',
    onProgress: 'onprogress',
    onRateChange: 'onratechange',
    onScroll: 'onscroll',
    onSeeked: 'onseeked',
    onSeeking: 'onseeking',
    onSelect: 'onselect',
    onStalled: 'onstalled',
    onSubmit: 'onsubmit',
    onSuspend: 'onsuspend',
    onTimeUpdate: 'ontimeupdate',
    onTouchCancel: 'ontouchcancel',
    onTouchEnd: 'ontouchend',
    onTouchMove: 'ontouchmove',
    onTouchStart: 'ontouchstart',
    onTransitionEnd: 'ontransitionend',
    onVolumeChange: 'onvolumechange',
    onWaiting: 'onwaiting',
    onWheel: 'onwheel' 
}

export const AMP_REGEXES_PRE = [
    /<html.*<\/head>/gimu,
    /<\/html/gimu,
    /\sstyle=".*?"/gimu,
    /\sstyle='.*?'/gimu,
    /\sscope=".*?"/gimu,
    /\ssummary=".*?"/gimu,
    /\sitem=".*?"/gimu,
    /\sitem='.*?'/gimu,
    /\salign='.*?'/gimu,
    /\svalign=".*?"/gimu,
    /\sv=".*?"/gimu,
    /\srules=".*?"/gimu,
    /\snowrap=".*?"/gimu,
    /\stype='.*?'/gimu,
    /\saria-describedby='.*?'/gimu,
    /\ssize=".*?"/gimu,
    /\sface=".*?"/gimu,
    /\scolor=".*?"/gimu,
    /\susemap=".*?"/gimu,
    /<html><head><\/head>/gimu,
    /<\/html>/gimu,
    /\sunselectable=".*?"/gimu,
    /\starget=".*?"/gimu,
    /\sonclick=".*?"/gimu,
    /\sonmouseout=".*?"/gimu
];
export const AMP_REGEXES_POST = [
    /border=".*?"/gimu,
    /pic_id=".*?"/gimu,
    /style=".*?"/gimu,
    /style='.*?'/gimu,
    /xml:lang=".*?"/gimu,
    /\sstyle="color:\s#71b8e4;"/gimu,
    /\sstyle="color:\s#71b8e4;\sfont-face:\sbold;\stext-decoration:\snone;"/gimu
];

export const URL_REGEX_TEST = /^(?:(?:https?|ftp):\/\/)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.​\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[​6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1​,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00​a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u​00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:\/[^\s]*)?$/i;
export const AMP_BAD_TAGS = [
    'audio',
    'head',
    'map',
    'math',
    'mi',
    'mo',
    'mtd',
    'mrow',
    'mspace',
    'mtext',
    'msub',
    'msup',
    'mstyle',
    'semantics',
    'usemap',
    'xml',
    'worddocument',
    'mathpr',
    'mathfont',
    'code',
    'picture'
];
export const AMP_BAD_CLASSES = [
    'mwe-math-fallback-image-inline',
    'sortkey',
    'mw-graph-img',
    'oly_at__img',
    'timeline-wrapper',
    'PopUpMediaTransform'
];